Lesson2
qa-guru/qa_guru_xctest_a4 pull request #5
Opened 2024-01-25 21:42 UTC by vasilyevit

прогон https://github.com/vasilyevit/qa_guru_xctest_a4/actions/runs/7660664721

2024-01-26 06:11 UTC, Monolith13 commented on .github/workflows/ios.yml
> +  TESTPLAN: ${{ inputs.tesplan || 'Debug' }}
Тут опечатка: "testplan" вместо "tesplan"

2024-01-26 06:18 UTC, Monolith13 requested changes
Все отлично 👍, прошу только поправить опечатку, так как из-за нее всегда будет значение по-умолчанию срабатывать

2024-01-26 07:58 UTC, vasilyevit commented on .github/workflows/ios.yml
> +  TESTPLAN: ${{ inputs.tesplan || 'Debug' }}
Спасибо, поправил.

2024-01-27 11:36 UTC, Monolith13 approved these changes

2024-01-27 11:37 UTC, Monolith13 commented
Домашнее задание принято ✅

2024-01-27 11:37 UTC, closed without merging